FROM clojure:alpine as builder
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY project.clj /usr/src/app/
RUN lein deps
COPY . /usr/src/app
RUN mv "$(lein uberjar | sed -n 's/^Created \(.*standalone\.jar\)/\1/p')" app-standalone.jar

#FROM openjdk:8-jre-alpine

#COPY --from=builder /usr/src/app/app-standalone.jar .

CMD ["java", "-jar", "app-standalone.jar"]
EXPOSE 7890
